insert into sport(name) values ("Cheerleading");
insert into sport(name) values ("Football");
insert into sport(name) values ("Field Hockey");
insert into sport(name) values ("Gymnastics");
insert into sport(name) values ("Men's Basketball");
insert into sport(name) values ("Men's Crew");
insert into sport(name) values ("Men's Ice Hockey");
insert into sport(name) values ("Men's Lacrosse");
insert into sport(name) values ("Men's Skiing");
insert into sport(name) values ("Men's Soccer");
insert into sport(name) values ("Men's Swimming & Diving");
insert into sport(name) values ("Men's Tennis");
insert into sport(name) values ("Men's Track & Field");
insert into sport(name) values ("Men's Cross Country");
insert into sport(name) values ("Softball");
insert into sport(name) values ("Women's Basketball");
insert into sport(name) values ("Women's Crew");
insert into sport(name) values ("Women's Golf");
insert into sport(name) values ("Women's Ice Hockey");
insert into sport(name) values ("Women's Lacrosse");
insert into sport(name) values ("Women's Skiing");
insert into sport(name) values ("Women's Soccer");
insert into sport(name) values ("Women's Swimming & Diving");
insert into sport(name) values ("Women's Tennis");
insert into sport(name) values ("Women's Track & Field");
insert into sport(name) values ("Women's Volleyball");
insert into sport(name) values ("Women's Cross Country");
insert into sport(name) values ("Wrestling");